### ISSUE TITLE
Windows 11 - návod

### ISSUE THREAD

**Issue by 1ucay** [setnicka/ulozto-downloader#101]
Ahoj, jelikož Vžum nefunguje, zkusil jsem tvůj projekt.
S Pythonem 3.9 a 3.10 mi nefungovalo. 

1. Odinstaloval jsem Python 3.10 a nainstaloval **3.8 x64** (s x86 nefunguje kvůli tensorflow!)
2. python -V
    musí ukazovat 3.8
3. python -m ensurepip --upgrade
4. python -m pip install --upgrade pip
   nainstaluje PIP
4. pip3 install --upgrade ulozto-downloader[auto-captcha]
5. python -m pip install wheel
6. python -m pip install tensorflow
7. Instalovat Tor Browser - pozor, pokud budete instalovat do Program Files, musíte nastavit složce práva (vlastnosti u C:\Program Files\Tor Browser\Browser;Zabezpečení,Upravit, Users (xxx), zaklikat )
8. V cmd "path" - musí bý složka, kde je tor.exe ( pokud není, přidat do PATH C:\Program Files\Tor Browser\Browser\TorBrowser\Tor ) - musí odkazovat na tor.exe
10. ulozto-downloader --parts 50 "https://ulozto.cz/file/TKvQVDFBEhtL/debian-9-6-0-amd64-netinst-iso"
   již by mělo captchu louskat a stahovat :)

TIP: vytvořte si ulozto.bat
ulozto-downloader --parts 100 "https://uloz.to/file/XXX"
del /S *.ucache
del /S *.udown

**Comment by honzikv** [comment]
Diky pomoci tohohle jsem to rozbehal.
Jeste pokud nekdo pouziva Pycharm tak divne instaluje tflite - takze doporucuji to nainstalovat primo pres anacondu

**Comment by regiss** [comment]
> Ahoj, jelikož Vžum nefunguje, zkusil jsem tvůj projekt. S Pythonem 3.9 a 3.10 mi nefungovalo.
> 
> 1. Odinstaloval jsem Python 3.10 a nainstaloval **3.8 x64** (s x86 nefunguje kvůli tensorflow!)
> 2. python -V
>    musí ukazovat 3.8
> 3. python -m ensurepip --upgrade
> 4. python -m pip install --upgrade pip
>    nainstaluje PIP
> 5. pip3 install --upgrade ulozto-downloader[auto-captcha]
> 6. python -m pip install wheel
> 7. python -m pip install tensorflow
> 8. Instalovat Tor Browser - pozor, pokud budete instalovat do Program Files, musíte nastavit složce práva (vlastnosti u C:\Program Files\Tor Browser\Browser;Zabezpečení,Upravit, Users (xxx), zaklikat )
> 9. V cmd "path" - musí bý složka, kde je tor.exe ( pokud není, přidat do PATH C:\Program Files\Tor Browser\Browser\TorBrowser\Tor ) - musí odkazovat na tor.exe
> 10. ulozto-downloader --parts 50 "https://ulozto.cz/file/TKvQVDFBEhtL/debian-9-6-0-amd64-netinst-iso"
>     již by mělo captchu louskat a stahovat :)
> 
> TIP: vytvořte si ulozto.bat ulozto-downloader --parts 100 "https://uloz.to/file/XXX" del /S *.ucache del /S *.udown

Nevite proc python 3.9 a 3.10 neni podporovan? 
Snazil jsem se pochopit zavislot balicku ale moje znalosti pip nejsou velke? Da se nekde vycist zavislosti? 
S pythnem 3.9 se automaticky pouzije stara verze ulozto-downloader-2.6.0 misto 3.1
a rucni doinstalovani vyhazuje chybu:

`pip3 install tflite-runtime
ERROR: Could not find a version that satisfies the requirement tflite-runtime (from versions: none)
ERROR: No matching distribution found for tflite-runtime`

**Comment by zbyna** [comment]
@regiss You have 2 options at least:
1. build yourself as mentioned here: https://discuss.tensorflow.org/t/how-to-install-tflite-runtime-in-windows-machine/11427
2. try this wheel for python 3.9 : https://github.com/google-coral/pycoral/releases/download/v2.0.0/tflite_runtime-2.5.0.post1-cp39-cp39-win_amd64.whl

I have not tested any of them.

**Comment by Vojtak42** [comment]
> 

S Pythonem 3.9.13 funguje bez problémů, musíte instalovat tensorflow z google pycoral.

**Comment by Vojtak42** [comment]
> Ahoj, jelikož Vžum nefunguje, zkusil jsem tvůj projekt. S Pythonem 3.9 a 3.10 mi nefungovalo.
> 
>     1. Odinstaloval jsem Python 3.10 a nainstaloval **3.8 x64** (s x86 nefunguje kvůli tensorflow!)
> 
>     2. python -V
>        musí ukazovat 3.8
> 
>     3. python -m ensurepip --upgrade
> 
>     4. python -m pip install --upgrade pip
>        nainstaluje PIP
> 
>     5. pip3 install --upgrade ulozto-downloader[auto-captcha]
> 
>     6. python -m pip install wheel
> 
>     7. python -m pip install tensorflow
> 
>     8. Instalovat Tor Browser - pozor, pokud budete instalovat do Program Files, musíte nastavit složce práva (vlastnosti u C:\Program Files\Tor Browser\Browser;Zabezpečení,Upravit, Users (xxx), zaklikat )
> 
>     9. V cmd "path" - musí bý složka, kde je tor.exe ( pokud není, přidat do PATH C:\Program Files\Tor Browser\Browser\TorBrowser\Tor ) - musí odkazovat na tor.exe
> 
>     10. ulozto-downloader --parts 50 "https://ulozto.cz/file/TKvQVDFBEhtL/debian-9-6-0-amd64-netinst-iso"
>         již by mělo captchu louskat a stahovat :)
> 
> 
> TIP: vytvořte si ulozto.bat ulozto-downloader --parts 100 "https://uloz.to/file/XXX" del /S *.ucache del /S *.udown

Stejné jako pro windows 10. Tensorflow instalujte ze souborů google pycoral, jsou tam novější verze.

**Comment by JanPalasek** [comment]
Další funkční způsob je přes WSL 2.

**Comment by 1ucay** [comment]
Ahoj, udělal jsem si EXE helper pro ty, co nemají rádi konzoli. Zabere Vám to minutu :)

1. Stáhněte si PowerShell builder https://github.com/MScholtes/Win-PS2EXE
2. Vytvořte soubor ulozto.ps1 v UTF-8
`Add-Type -AssemblyName Microsoft.VisualBasic
$URL = [Microsoft.VisualBasic.Interaction]::InputBox('Zadejte URL souboru', 'Uloz.to', "https://uloz.to/file/YPivhc3Jyn9r/debian-live-11-1-0-amd64-mate-iso#!ZGyxLwR2AzDmZmIzLGH4AGxmAzIvMKV5oayypHZkHayUZGZ1LD==")
$PARTS = [Microsoft.VisualBasic.Interaction]::InputBox('Počet částí', 'Uloz.to', "50")
Start-Process -FilePath "ulozto-downloader" -ArgumentList ('--parts ' + $PARTS + ' "' + $URL + '"')`
3. Stáhněte si https://uloz.to/favicon.ico
4. Spusťte Win-PS2EXE.exe, nastavte ulozto.ps1 a favicon.ico a dejte Compile :)

**Comment by Vojtak42** [comment]
> Další funkční způsob je přes WSL 2.

Bohužel nějak nevidím výhodu WSL 2, stále problém s pythonem 3.10.

**Comment by JanPalasek** [comment]
> > Další funkční způsob je přes WSL 2.
> 
> Bohužel nějak nevidím výhodu WSL 2, stále problém s pythonem 3.10.

Mam python 3.8. Vyhoda je v tom, ze nemusis resit rucni stahovani toru na windowsu a davat ho do cesty, a nemusis resit stahovani tensorflow bokem. Proste funguje oficialni navod.

**Comment by Vojtak42** [comment]
Pokud máš na windows python 3.8, tak taky nemusíš řešit stahování tensorflow bokem

**Comment by 1ucay** [comment]
Casem bude i pro Python 3.10 tflite-runtime, ale zatim neni :) Jinak cele to nastavit dle navodu zabere 5-10 minut...

**Comment by Vojtak42** [comment]
Ono je to na pc jednoduché i bez návodu, to android mi to bez návodu zabralo asi 3 dny.

**Comment by majsnerkomenz** [comment]
Ahoj, nevíte někdo co s tím, postupoval jsem dle návodu z webu..
![image](https://user-images.githubusercontent.com/114443109/192374915-a61f1691-74bc-41a6-a5aa-0bf0b8233132.png)

**Comment by Vojtak42** [comment]
`pip install --upgrade ulozto-downloader`

**Comment by majsnerkomenz** [comment]
> `pip install --upgrade ulozto-downloader` Zkontroluj si, že máš verzi 3.1.0 (`ulozto-downloader --version`).

To pomohlo díky. Teď bych ještě potřeboval zprovoznit auto captchu, zkoušel jsem vložit "--auto-captcha" to ale hodí jen chybu. A když stahování zapnu tak musím vyplňovat ručně
![image](https://user-images.githubusercontent.com/114443109/192464076-baa84290-fd70-457a-9d7d-427bb192b844.png)

**Comment by majsnerkomenz** [comment]
> `pip install --upgrade ulozto-downloader` Zkontroluj si, že máš verzi 3.1.0 (`ulozto-downloader --version`).
Ještě bych potřeboval zprovoznit tu autocaptchu, zkoušel jsem vložit "--auto-captcha" ale to hodí jen chybu. A když běží stahování tak musím vypisovat ručně

![image](https://user-images.githubusercontent.com/114443109/192470348-d35031ca-84bd-4dc6-a499-58fd009bf966.png)

**Comment by Vojtak42** [comment]
Nedokázal bys vyfotit, co za chybu to napíše?

**Comment by majsnerkomenz** [comment]
> Nedokázal bys vyfotit, co za chybu to napíše?
Jistě

![image](https://user-images.githubusercontent.com/114443109/192483614-4e1804df-d272-46ca-8ab4-22598cabca8c.png)

**Comment by Vojtak42** [comment]
A píšeš tam `ulozto-downloader --auto-captcha "url"`, když se něco snažíš stáhnout?

**Comment by Vojtak42** [comment]
A píšeš tam `ulozto-downloader --auto-captcha "url"`, když se něco snažíš stáhnout?

**Comment by Vojtak42** [comment]
Poslední příkaz je ten správný. Jdi na google pycoral a stáhni si tflite_runtime pro tvoji platformu

**Comment by Vojtak42** [comment]
https://github.com/google-coral/pycoral/releases/tag/v2.0.0

**Comment by Vojtak42** [comment]
Ps to se dělá tak, že program navedeš do složky, kde máš stažený soubor a zadáš: `pip install [název staženého souboru]`

**Comment by majsnerkomenz** [comment]
> No jenže ten tflite_runtime tam není pro 3.10.   A když stáhnu 3.8. tak to je prostě jen ve složce a jaksi to společně nekomunikuje a zas nevím co s tim ☹
![image](https://user-images.githubusercontent.com/114443109/192512494-a2f2a716-c1b7-45d3-a9cd-5086c41efa0f.png)

**Comment by Vojtak42** [comment]
Auto-captcha není lehce kompatibilní s pythonem 3.10, to by sis musel ten program sám sestavit z programu. Lehčí je si nainstalovat python 3.9.

**Comment by Vojtak42** [comment]
PS mzsíš být ve stejné složce jako ten soubor.whl (pokud sis ho nepřesunul do té složky pythonu v appdata.

**Comment by majsnerkomenz** [comment]
> pip install --upgrade ulozto-downloader

Už to funguje, díky moc

**Comment by setnicka** [comment]
Tohle vypadá vyřešeně, zavírám.

Část s vytvořením Windows EXE souboru ještě hodím do dokumentace.
