### ISSUE TITLE
Mazání souborů .ucache a .udown po dokončení stahování

### ISSUE THREAD

**Issue by engycz** [setnicka/ulozto-downloader#103]
Po dokončení stahování ty soubory už asi k ničemu nejsou

**Comment by setnicka** [comment]
Některé implementace (#105) je používají. Ale pravda, že pro běžného uživatele mohou být spíše otravné.

Asi by stálo za to pořádně rozmyslet, jak s nimi nakládat a kdy je odstraňovat/neodstraňovat (a schovat to pod nějaké flagy nebo nastavení frontendů).

**Comment by SpiReCZ** [comment]
V mých úpravách se tento soubor maže v cmd.py namísto v Downloader class, takže je zajištěno funkcionalita pro oba způsoby použití. https://github.com/setnicka/ulozto-downloader/pull/105/files#diff-aa21c66c4d4027469e63ff5ffc6ab126c2ea9e100fd21ce65867d9ed0692d2b1R91

**Comment by setnicka** [comment]
`.udown` soubor se teď ve verzi 3.2.0 automaticky maže, `.ucache` zůstává pro případný restart stahování.

Zatím občas straší nějaké případy, kdy umře stahování nějaké části a pak stačí spustit stejný příkaz znovu a dostahovat scházející část. Zamyslím se ještě, jestli by nedávalo smysl v případě úspěchu i `.ucache` smazat :thinking:

**Comment by setnicka** [comment]
V nové verzi 3.3.0 se soubory po úspěšném dostahování samy mažou, IMHO po úspěšném dostahování nejsou potřeba (samozřejmě při chybě tam zůstanou). Je to implementované jenom v `cmd.py`, takže by to nemělo nijak negativně ovlivnit věci, které ulozto-downloader používají jako knihovnu.
