### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by aleqcz** [setnicka/ulozto-downloader#104]
Ahoj,
nevíte někdo co tomu je? Nejsem Pythonista, tak s tím trochu bojuju. Nepouští to náhodou Pyton 2.7?

`~/dl>ulozto-downloader
Traceback (most recent call last):
  File "/home/aleq/.local/bin/ulozto-downloader", line 8, in <module>
    from ulozto_downloader import downloader, captcha
  File "/home/aleq/.local/lib/python3.5/site-packages/ulozto_downloader/downloader.py", line 73
    cli_initialized: bool
                   ^
SyntaxError: invalid syntax
`

Díky

**Comment by setnicka** [comment]
Ahoj, podle výpisu, co posíláš, to pouštíš v Pythnou 3.5 – ten už je hodně starý (dokonce do září 2020 už je po end-of-life a neyvchází pro něj už žádné aktualizace) a tak doporučím Python aktualizovat.

Minimální podporovaná verze Pythonu pro ulozto-downloader je Python 3.7.
