### ISSUE TITLE
CAPTCHA focus

### ISSUE THREAD

**Issue by mkroulik** [setnicka/ulozto-downloader#106]
Při ručním zadávání kódu captcha, od druhého obrázku již není focus na input textového pole a je nutné, před zadáním kódu, pokaždé myší do pole kliknout.

**Comment by setnicka** [comment]
Zajímavé, tohle dříve fungovalo. Na jakém systém (Win/Linux) se to děje? Zkusím prozkoumat.

**Comment by mkroulik** [comment]
> Zajímavé, tohle dříve fungovalo. Na jakém systém (Win/Linux) se to děje? Zkusím prozkoumat.

Win 11, .NET framework 4.8.4084.0.

**Comment by setnicka** [comment]
Testoval jsem na Linuxu i na Win 11 a text input focus vždycky dostal :shrug: 

Kontroloval jsem, že v kódu stále je provolání `.focus()`, když okno zobrazíme. Takže neumím reprodukovat :(

**Comment by setnicka** [comment]
Zavírám pro nereprodukovatelnost. Pokud se to objeví znovu, klidně issue znovuotevřeme.
