### ISSUE TITLE
Jeden súbor sa nestiahne celý

### ISSUE THREAD

**Issue by Sperhak323** [setnicka/ulozto-downloader#107]
Každé sťahovanie mi skončí tak že z jedného partu sa kúsok nestiahne. Sťahovanie sa úspešne dokončí a súbor nevyzerá byť poškodený. Tak neviem či je to je vážna chyba, alebo len vizuálna že v skutočnosti sa ten part stiahne celý.

**Comment by setnicka** [comment]
Očekával bych spíše chybku v zobrazování statusu, že se nezavolá poslední vykreslení ale program se ukončí dřív. To by snad mělo být lehké fixnout, podívám se na to.

**Comment by Sperhak323** [comment]
Pridávam screen
![image](https://user-images.githubusercontent.com/73948698/188127844-56603506-55f9-4081-a4c2-6938f3b532f8.png)
