### ISSUE TITLE
'--output' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Vojtak42** [setnicka/ulozto-downloader#109]
![output](https://user-images.githubusercontent.com/18753137/189502011-385d357c-4722-479b-9abb-162a08e325d6.png)

**Comment by Vojtak42** [comment]
It always worked, I have not installed any update and this showed.

**Comment by setnicka** [comment]
Sorry for late reply.

It looks like a typo, the command is `>ulozto-downloader --output...`. The `>` at the start is "redirect output of this command to the file `ulozto-downloader` and the first part `--output` is then interpreted as the name of the command... which of course doesn't exist.
