### ISSUE TITLE
Wrong UI displaying

### ISSUE THREAD

**Issue by Pheggas** [setnicka/ulozto-downloader#110]
I've had issues with this over a long time. The UI shows only first X parts that fits onto screen, but even after they're done, they are still present on screen:

![image](https://user-images.githubusercontent.com/9994511/189514931-caf6bdf3-5d3e-4768-94d8-3dbde522588f.png)

Successfully downloaded parts still present on screen:
![image](https://user-images.githubusercontent.com/9994511/189514939-7bc41acb-ad6c-40c3-ad63-ee985eb04d9e.png)

Resulting in screen like this:
![image](https://user-images.githubusercontent.com/9994511/189514949-e369be24-67b9-4f17-bb75-eb5de1cedddc.png)

Which is filled with useless information as download is still in progress and i can't see progress of new parts.

**Comment by setnicka** [comment]
Thanks to above pull request this should be solved now, update to version 3.2.0:
```shell
pip3 install --upgrade ulozto-downloader
```

By default parts progress is hidden. It could be displayed by `--parts-progress` switch but the overall status is now on the top.
