### ISSUE TITLE
what to do? hergot.

### ISSUE THREAD

**Issue by hapashtiepa** [setnicka/ulozto-downloader#116]
![Screenshot_2022-09-19_18_54_43](https://user-images.githubusercontent.com/113451474/191071712-157a8be3-bc9c-473f-8837-bc31a7a67e9d.png)

**Comment by ParaLizzard** [comment]
Write ulozto-donwloader --parts 30 "URL".

**Comment by Vojtak42** [comment]
Try read what it writes. You don't have tensorflow

**Comment by Vojtak42** [comment]
And tflite_runtine doesn't work on python3.10

**Comment by ParaLizzard** [comment]
Python 3.8 needed

**Comment by Vojtak42** [comment]
I dont understand what you mean by your answer but it works on python 3.8. just download it from google pycoral repository.

**Comment by setnicka** [comment]
Just released version 3.2.0 should solve this issue, because it could also use `tensorflow.lite` instead of the `tflite-runtime`, which isn't available for newer Pythons. See README for install instructions.

Closing this issue now, reopen if needed.
