### ISSUE TITLE
Help needed to make it work

### ISSUE THREAD

**Issue by GarmenCZE** [setnicka/ulozto-downloader#124]
I am trrying to install it and I got the module to respond to my commands but I cant get tor to work, I did edit the process.py and put a path to the tor.exe there but still it doesnt work.

**Comment by sssimon-phoenix** [comment]
In current version of python I had also issues. But in 3.7 works OK.
(update pip :-) )
(do you have python itself in path?)

**Comment by GarmenCZE** [comment]
I dont know, I only followed the instructions on how to add tor to the path but I dont have any experience with python.

**Comment by setnicka** [comment]
I updated the README with a better install guide. Does it help?

Also ulozto-downloader version 3.2.0 should work both with `tflite-runtime` and `tensorflow.lite`, which should solve problems with auto-CAPTCHA on newer Pythons, see README.

**Comment by setnicka** [comment]
Closing as stale and probably fixed by updated README.
