### ISSUE TITLE
Infinite captcha loop

### ISSUE THREAD

**Issue by SpiReCZ** [setnicka/ulozto-downloader#126]
From what i can tell, there are some downloads that cannot be downloaded with current system.

Great example: https://tinyurl.com/2fc9suhu
Captcha is solved correctly with auto solver and i even tried a manual one.

But download page always returns title: `Pro Pomalé stažení opište kód z obrázku`.

**Comment by zbyna** [comment]
Above-mentioned file downloaded with these results:
![](https://i.imgur.com/BrUhZdU.png) and plays well.

**Comment by SpiReCZ** [comment]
version: 3.1.0
python: 3.9.15
os: linux x64

I was able to download that file later, however no other files from list of the same title and same uploader.
I guess this might be something related to the tor network usage and requesting captchas too quickly.

another:
https://tinyurl.com/yx6mvzfs
https://tinyurl.com/43dve2kc
https://tinyurl.com/42fmbmcc

**Comment by SpiReCZ** [comment]
If i change the url (domain) from `https://www.uloz.to/file/` to `https://ulozto.cz/file/`... The downloading work as expected.

**Comment by SpiReCZ** [comment]
classic URL: `https://uloz.to/file/` seems to be working fine.

**Comment by zbyna** [comment]
@SpiReCZ great testing!
I tend to think this issue lies out of ulozto-downloader source code.

**Comment by SpiReCZ** [comment]
@zbyna thx, i am just glad i was able to make it working after all. It is not the best thing to do, but if this happens again there is a possibility to rewrite the URL to working one. I will leave the issue open, since the issue is still there.

**Comment by setnicka** [comment]
Closing this old issue, it seems that nowaday wors all URL variants (uloz.to, www.uloz.to, ulozto.cz, ...).
Fixed on the UlozTo side :)
