### ISSUE TITLE
Tor - private directory

### ISSUE THREAD

**Issue by hundera** [setnicka/ulozto-downloader#131]
Po (poslední?) aktualizaci mi přestalo fungovat stahování

_Tor start failed: Process terminated: Couldn't create private data directory "/srv/..../filmy/tor_data_dir_84...995", exiting. Try run program again._

Stahuju soubor pomocí přepínače --output na přimountovaný disk s FAT systémem, takže tam asi nedovede udělat adresář se správným oprávněním. Pokud stahuju do domovského adresáře je vše ok (ale na raspberry moc místa není).

Dříve to fungovalo - nezměnilo se nějak volání toru?
Zkoušel jsem v /etc/tor/torrc nastavit DataDirectory, ale to nemá vliv.

díky
Ondřej

**Comment by MarekVigas** [comment]
Tiez som si vsimol tento problem. V predchadzajucich verziach sa tor folder vytvaral v current working directory, momentalne sa vsak pokusa vytvorit tor folder v output. Myslim si ze by mal vzniknut dalsi prepinac na folder pre obsluzne data ako tor a do output zapisovat iba vysledny stahovany subor. WDYT @setnicka

**Comment by setnicka** [comment]
Během svátků se zkusím k ulozto-downloaderu zase dostat a vyladit pár věcí, mimo jiné i tohle. Bohužel času je málo a projektů a práce spousta, takže se nedostávám k ulozto-downloaderu tak často, jak by si zasloužil.

**Comment by setnicka** [comment]
Právě jsem publikoval verzi 3.3.0, ve které by mělo být možné nastavit si separátně output dir (option `--output`) pro výsledný soubor a temp dir (option `--temp`) pro všechny pomocné soubory. To by mělo s tímto pomoci :)

**Comment by hundera** [comment]
Díky moc, funguje perfektně.
