### ISSUE TITLE
Tor failed to start

### ISSUE THREAD

**Issue by Marikoscz** [setnicka/ulozto-downloader#133]
Zdravím,
dost často se mi stává (ale ne pokaždé), když stahuji X souborů za sebou pomocí scriptu, že se TOR nezapne, sekne na X%, a po uplynutí 90 sekund failne. Nicméně mě zajímá, zda to jde, konkrétně v bashi, nějak ošetřit, aby, když Tor failne při zapínání, aby se pokusil opět stahování daného souboru zahájit. Zkoušel jsem to pomocí $?, ten je ale vždycky 0, protože to bere jen příkazy pouze mnou ručně zadané, čili ať mi Tor selže nebo ne, stejně se onen soubor nikdy nebude pokoušet stáhnout znovu.
Zkoušel jsem také přesměrování stderr, nebo stdout, ale nevím, jak současně stdout/stderr přesměrovat do proměnné, a zároveň zobrazovat průběh příkazu v Terminálu, protože byť mi toto řešení fungovalo, tak jsem ale neměl přehled o stahování souboru, jedině v případě chyby, a ta se mi, díky echu, zorbazila až po skončení příkazu.

Mimochodem to, že TOR se nepodaří nastartovat během 90s se mi stává i když příkaz pouštím samostatně ručně v terminálu, ale jsem si vědom, že je to způsobeno převážně opravdu low hardwarem, kterým disponuji.
Pro představu jedná se o LUBUNTU 20.04.5, 4GB RAM, Intel Atom C2350 - 1.7 GHz - 2 core(s) (vím, je to shitka, ale na mé potřeby, především díky ceně, stačí)

Kdyby někoho napadlo, jak to ošetřit, budu moc rád.
Příklad kódu, který jsem zkoušel, ale jak jsem popsal výše, tak $? je vždy 0
```
#!/bin/bash
input="/home/marikoscz/link"
while IFS= read -r line
do

 echo no |  ulozto-downloader --output '/home/marikoscz/Downloads/Ulozto' --auto-captcha --parts 150 "$line"	
echo $?
	while [ $? -ne 0 ]
		do
echo no |  ulozto-downloader --output '/home/marikoscz/Downloads/Ulozto' --auto-captcha --parts 150 "$line"


		done
done < "$input"
```

**Comment by Kucheek** [comment]
Tor je spouštěn pomocí Stemu (více [zde](https://stem.torproject.org/api/process.html)) a defaultní timeout je 90s. Jako rychlý workaround by to mohlo jít vyřešit úpravou volání Toru, zadáním vlastní vyšší hodnoty timeoutu (zatím jsem to nezkoušel). 

Konkrétně v souboru torrunner.py na řádku 84, takto:

![image](https://user-images.githubusercontent.com/6707809/203413767-0707db95-23c4-45d8-8a24-a46cd4ccc22f.png)

**Comment by Marikoscz** [comment]
Ok, díky, zkusím
