### ISSUE TITLE
Problem with password argument

### ISSUE THREAD

**Issue by Fikus25** [setnicka/ulozto-downloader#152]
Hello, 
I installed all the required tools for proper work of this program, but I noticed it doesn't recognize password argument, am I doing something wrong? I tried to test one of those commands in description:

`ulozto-downloader --parts 30 --password akcniset "https://uloz.to/file/FFwsQeBeMdcY/debian-9-6-0-amd64-netinst-iso"`

but it gives me an error: ulozto-downloader: error: unrecognized arguments: --password

Downloading files without password works good.

**Comment by setnicka** [comment]
Hello,

the version with the password was not yet been released (the last release on PyPI is 3.3.1 from January, this change was made in February). I thought I would be able to release a new version in February, but I had very little time for this project. I will try to push on it in the near future, review a few other issues and pull requests and release a new version soon.

**Comment by Fikus25** [comment]
Ok, thanks I was little bit confused because it was mentioned in the description. I'll wait for the next version.

**Comment by setnicka** [comment]
Version 3.4.1 was just released, it contains the password handling (by `--password` or by user prompt during the download).
