### ISSUE TITLE
tensorflow instalacia

### ISSUE THREAD

**Issue by bt4ibwem8** [setnicka/ulozto-downloader#162]
funguje vam instalacia tensorflow? skusam lite, ale aj plnu verziu ale vzdy dostanem toto:

![image](https://user-images.githubusercontent.com/114884026/234699152-14c90336-7a89-458a-aff6-a8be59671e1d.png)

**Comment by milos7250** [comment]
Ak som spravne dedukoval z obrazku, snazis sa nainstalovat TensorFlow na 32-bitovy Windows 7... Oficialne je vsak podporovany len pre 64-bitove systemy. TensorFlow nedistribuuje prekompilovane subory pre 32-bitove systemy, a teda ich pip ani nema sancu najst.

Riesenie by mohlo byt skompilovat TensorFlow manualne, no to je urcite viachodinova zalezitost, to sa radsej oplati dat subor z ulozto stiahnut priamo na noc.

**Comment by bt4ibwem8** [comment]
Je to 64-bit win7

**Comment by bt4ibwem8** [comment]
Verziu pythonu mam 3.11.3

![image](https://user-images.githubusercontent.com/114884026/235212877-1c3fcafc-26a8-48dd-8115-dd1139c0b96c.png)

**Comment by Petrxy** [comment]
Tak zkus nižší verzi Pythonu. Ta verze 3.11.3 je asi moc čerstvá a TensorFlow pro ní nejspíš není dostupný.

**Comment by milos7250** [comment]
tiez sa oplati skontrolovat ci sam Python je tiez 64-bit verzia

**Comment by bt4ibwem8** [comment]
@milos7250 mas pravdu, mal som omylom nainstalovanu 32-bit. Tu verziu mi chybne nainstaloval **_scoop_** a ja som si to nevsimol. Takze plny tensorflow (light verzia nesla) je uz nainstalovany v poriadku, ale ulozto-downloader mi dava tuto chybu:

![image](https://user-images.githubusercontent.com/114884026/235325411-15904999-6653-487c-8ea7-e26a220da0b8.png)

**Comment by bt4ibwem8** [comment]
tak som problem vyriesil downgrade pythonu na verziu `3.9.16` s ktorou ulozto-downloader funguje. Mozno je to problem len win7 ak vo win10/win11 to funguje aj s verziou 3.11
