### ISSUE TITLE
Nevi nekdo jak fixnout tenhle error?

### ISSUE THREAD

**Issue by LixCZ** [setnicka/ulozto-downloader#164]
[error.txt](https://github.com/setnicka/ulozto-downloader/files/11361012/error.txt)

**Comment by moimg40** [comment]
Dobré odpoledne!
Od dnešního dne mám také stejný problém, doufám, že to brzy vyřeší, protože mám několik souborů ke stažení.

**Comment by DavidJares** [comment]
https://github.com/setnicka/ulozto-downloader/issues/157

**Comment by setnicka** [comment]
Duplicate of #157
