### ISSUE TITLE
Version 3.5.1 fails to execute on Linux due to colorama

### ISSUE THREAD

**Issue by realcharmer** [setnicka/ulozto-downloader#165]
Running on Void Linux with `colorama` on version `v0.4.5`. Is this strictly dependent on `v0.4.6`? Version locks should be included in `requirements.txt`.

```
[Autodetect] tkinter available, using --manual-captcha
Traceback (most recent call last):
  File "/bin/ulozto-downloader", line 33, in <module>
    sys.exit(load_entry_point('ulozto-downloader==3.5.1', 'console_scripts', 'ulozto-downloader')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uldlib/cmd.py", line 124, in run
    from colorama import just_fix_windows_console
ImportError: cannot import name 'just_fix_windows_console' from 'colorama' (/usr/lib/python3.11/site-packages/colorama/__init__.py)
```

**Comment by JackPieCZ** [comment]
Simply run `pip install -U colorama` which will update `colorama` to the latest version. See the following [article](https://stackoverflow.com/questions/74654425/why-i-receive-importerror-cannot-import-name-just-fix-windows-console-from-c) for more details.

**Comment by realcharmer** [comment]
Yes, but requirements do not specify this constraint. This should be explicitly set as `>=0.4.6` to avoid these sorts of problems. This goes for all dependencies.

**Comment by JackPieCZ** [comment]
Yeah, you are right. Open a merge request for that if you feel like it
