### ISSUE TITLE
Cloudflare 2 error

### ISSUE THREAD

**Issue by LPbigFish** [setnicka/ulozto-downloader#168]
Dnes se mi ukázal tento error:

```Network error get new TOR connection: Cloudflare scrapper error: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.. Try new TOR session.```

Nebyl na uložto nějaký nový update?

**Comment by kkoouu** [comment]
to same u me :(

**Comment by RealAnthony0001** [comment]
https://github.com/setnicka/ulozto-downloader/issues/157#issuecomment-1535820190
