### ISSUE TITLE
[Feature] Dockerization

### ISSUE THREAD

**Issue by Pheggas** [setnicka/ulozto-downloader#171]
Hello. I'm using Docker to containerize my apps. I'd like to use this downloader in container as well. Will it be possible in the future. Right now i have dedicated minimal LCX on Proxmox for this app but i would like to include it among other my apps on main virtual machine.

**Comment by MarekVigas** [comment]
Check #130

**Comment by Pheggas** [comment]
But it's not yet merged, right?

**Comment by MarekVigas** [comment]
It is not merged. That PR contains a working Dockerfile and you can build the image yourself until it is merged. I suggest closing this issue and giving 👍🏻 to the #130 PR.

**Comment by Pheggas** [comment]
Alright
