### ISSUE TITLE
Error: Error solving the challenge. Timeout after 90.0 seconds.

### ISSUE THREAD

**Issue by Bob4716** [setnicka/ulozto-downloader#176]
log:
Cloudflare WAF detected, initializing automated Cloudflare Solver (timeout 92s).
Cannot download file: Cloudflare solver error: Error: Error solving the challenge. Timeout after 90.0 seconds.
Terminating download. Please wait for stopping all threads.
Download terminated.

a log z flaresolverr:
2023-09-01 21:09:17 INFO     Incoming request => POST /v1 body: {'maxTimeout': 92000, 'proxy': {'url': 'socks5://127.0.0.1:9050'}, 'session': '0c267bc5-48fb-11ee-a5f0-ed0112c4b4d5', 'url': 'https://uloz.to/file/TBpnowDbpRoh/odkaz-dracich-jezdcu-bonus-rar', 'cmd': 'request.get'}
2023-09-01 21:09:21 INFO     Challenge detected. Title found: Just a moment...
2023-09-01 21:10:49 ERROR    Error: Error solving the challenge. Timeout after 92.0 seconds.
2023-09-01 21:10:49 INFO     Response in 92.124 s
2023-09-01 21:10:49 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 500 Internal Server Error
2023-09-01 21:10:49 INFO     Incoming request => POST /v1 body: {'cmd': 'sessions.destroy', 'session': '0c267bc5-48fb-11ee-a5f0-ed0112c4b4d5'}
2023-09-01 21:10:50 INFO     Response in 0.172 s
2023-09-01 21:10:50 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK

zkusil jsem to změnit na 92 (příkazem --cf-timeout 92)  jak vidíte v  flaresolverr ale ukázala se stejná chyba

jenom změní:
Response in 0.172 s
Response in 0.359 s

a opravdu nevím v čem je chyba
![chyba](https://github.com/setnicka/ulozto-downloader/assets/96495576/80322767-8731-4a84-8243-eb9353177e41)

prosím pomoc.

**Comment by filo891** [comment]
Chyba je v tom, ze Flaresolverr si nevie poradit s captchou do zadaneho casoveho limitu. Zial, Downloader s tym vela narobit nevie. Odporucam skusit nasledovne, ci nieco pomoze:
* Skusit najnovsiu verziu Flaresolverr-u (3.3.3 - vysla vcera)
* Zvysit vyrazne timeout (napr. na nielkolko minut `--cf-timeout 300`)
* Spustit flaresolverr v headed mode `export HEADLESS=false` resp. `set HEADLESS=false` na Windowse.

Posledna moznost pravdepodobne pomoze, ale vyzaduje si to interakciu (napr. pohyb kurzorom) s oknom prehliadaca a dost to znizuje privetivost pouzivania downloaderu.

**Comment by Bob4716** [comment]
ona vyšla nova verze Flaresolverr? to sem nevěděl díky

1. krok - stejná chyba

2. krok -  úplně stejná chyba (Internal Server Error)

3. krok - nevím jak to zpustit ale dal jsem do terminálu `set HEADLESS=false` a zapl laresolverr, a stejná chyba (zkusil jsem to dat i do terminálu kde mam donwloader ale něco dělam špatně asi.... nevím co stým :D

**Comment by filo891** [comment]
> nevím jak to zpustit ale dal jsem do terminálu `set HEADLESS=false` a zapl laresolverr, a stejná chyba (zkusil jsem to dat i do terminálu kde mam donwloader ale něco dělam špatně asi.... nevím co stým :D

Flaresolverr musi byt spusteny z rovnakeho terminalu kde je nastavena premenna `HEADLESS`, potom sa nou bude riadit.

**Comment by Scavy** [comment]
CloudFlare changed their verification challenge, so that the field that is supposed to be ticked has changed it's name.
We have to wait for FlareSolverr to be updated.
See: https://github.com/FlareSolverr/FlareSolverr/issues/881
And:   https://github.com/FlareSolverr/FlareSolverr/pull/882

Keep in mind this is related to the Pull Request on this repo: https://github.com/setnicka/ulozto-downloader/pull/173

And not on the standard version of Ulozto-Downloader.

**Comment by Bob4716** [comment]
> > nevím jak to zpustit ale dal jsem do terminálu `set HEADLESS=false` a zapl laresolverr, a stejná chyba (zkusil jsem to dat i do terminálu kde mam donwloader ale něco dělam špatně asi.... nevím co stým ![:D](https://static-cdn.jtvnw.net/emoticons/v2/3/default/light/1.0)
> 
> Flaresolverr musi byt spusteny z rovnakeho terminalu kde je nastavena premenna `HEADLESS`, potom sa nou bude riadit.

ano stáhlo se to už pohodě jen se zapl zvlášť prohlížeč a chtělo to jen zaškrtnout autorizaci a capcu to dělalo samo. děkuji mockrát za pomoc

**Comment by Bob4716** [comment]
> CloudFlare changed their verification challenge, so that the field that is supposed to be ticked has changed it's name. We have to wait for FlareSolverr to be updated. See: [FlareSolverr/FlareSolverr#881](https://github.com/FlareSolverr/FlareSolverr/issues/881) And: [FlareSolverr/FlareSolverr#882](https://github.com/FlareSolverr/FlareSolverr/pull/882)
> 
> Keep in mind this is related to the Pull Request on this repo: #173
> 
> And not on the standard version of Ulozto-Downloader.

okay thanks
