### ISSUE TITLE
Konec nebo další clona?

### ISSUE THREAD

**Issue by SpiReCZ** [setnicka/ulozto-downloader#185]
https://uloz.to/faq#backup
Vypadá to, že se buď stahují mračna a nebo bude další větší separace služeb.
Ani bych se nedivil, kdyby se najednou objevila aplikace "třetí strany" s přístupem na jejich API s vyhledáváním nebo na sdílení linků.

**Comment by Vojtak42** [comment]
Snad- ale radši stahuju, co chci.

**Comment by SpiReCZ** [comment]
je to tady

**Comment by Vojtak42** [comment]
Gozo pořád funguje, ale stahovat nejde.

**Comment by stinovlas** [comment]
Možná. Point byl v tom, že z Ulož.to šlo stahovat od libovolného místa souboru (offset), což umožňovalo rychlé vícevláknové downloady. Těžko říct, jestli něco podobného půjde najít jinde a pokud ano, jestli obsah bude stát za tu práci, která by s tím byla.

**Comment by Vojtak42** [comment]
Teď určitě ne.

**Comment by Vojtak42** [comment]
Tak ulozto stále funguje, jdownloader2 stahuje bez peoblémů.

**Comment by Vojtak42** [comment]
Tak možná by se to dalo fixnout:

> Free stahování z Ulozto:
>
> 1) Vyhledat soubor:
> `https://gozofinder.com/cse/ulozto/cz`
>
> 2) ID souboru:
>
>
>
> 3) Free stažení:
> `https://uloz.to/download-dialog/free/download?fileSlug=`
> Za = okopírovat dané ID
>
> 4) Ve Firefoxu stisknout F12 -> opsat Captcha a potvrdit. Kolečko se bude točit. V "Síť" vyhledat "json" -> Odpověd" -> okopírovat Link na greencdn
>
>
> 5) Stahuješ
>
>
> Respekt a Credits @yellow123

**Comment by Fikus25** [comment]
Tady je videonávod pro ty, kteří ještě neví jak na to, návod je pro prohlížeč Opera, ale funguje to všude +- stejně.
[](https://youtu.be/vDfD2Hk9WMg)

**Comment by mojucet666** [comment]
Mně to tam hodí hlášku "Na požadovanou akci nemáte oprávnění" :(
