### ISSUE TITLE
TOR get new captcha (timeout 30) (co mám udělat?)

### ISSUE THREAD

**Issue by TheGuyOnChair** [setnicka/ulozto-downloader#187]
Zdravíčko, 

již před delší dobou mi přestal fungovat program Vžum a tak jsem se rozhodl si nainstaloval "ulozto-downloader", postupoval jsem podle návodu, tzn, že jsem si stáhl python (zaškrtl PATH), nainstaloval TOR, zadal jej do proměnného prostředí. 

nainstaloval TensorFlow Lite přes adm. cmd -> pip3 install tensorflow
TKinder jsem se pokoušel instalovat, ale píše mi to tohle (viz screenshoty)
následně pip3 install --upgrade ulozto-downloader [auto-captcha]

![wtff 2](https://github.com/setnicka/ulozto-downloader/assets/152231764/8ffe2a04-2f01-40f2-8f67-c39a8861ae83)
![wtff 3](https://github.com/setnicka/ulozto-downloader/assets/152231764/39ac694a-5fbf-4976-9954-3a2dc4e03d85)
![wtff](https://github.com/setnicka/ulozto-downloader/assets/152231764/7cb97e71-2cd6-4a00-86b9-f21d746478a9)

Netuším vážně, co s tímhle dále dělat, ani jak pořádně používat ten command. 
usage: ulozto-downloader [-h] [--parts N] [--output DIRECTORY] [--auto-captcha] [--version] 

Zatím jsem používal tohle: ulozto-downloader +(url)

Je tu prosím někdo, kdo se v tom aspoň trochu vyzná a ví co dělá, popřípadě, funguje Vám ten program ještě vůbec ?
Projížděl jsem si i sekci Issues, prozkoušel různé verze, od ulozto-downloader az po python. Je to furt stejné.
Díky za odpověď

**Comment by TheGuyOnChair** [comment]
no čau čau, tak jsem tu zpátky po 8 hodinách, tak nevím, jak se mi to podařilo, ale díky tomuhle vláknu https://github.com/setnicka/ulozto-downloader/issues/101 se mi podařilo už něco stáhnout, ale stejně mě zarazilo, že to stahovalo pouze rychlostí 170kb/s a ne rychleji. nevíte někdo, co zase s tím? :D se z toho picnu už

**Comment by TheGuyOnChair** [comment]
![30](https://github.com/setnicka/ulozto-downloader/assets/152231764/b5074a22-4cd3-40b2-82d8-5409ba879d89)

**Comment by Mikkauser** [comment]
Pekny den, prosim ktory fork momentalne funguje s rychlejsim stahovanim? Niekto v starych vlaknach doporucil pouzit nizsiu verziu, ale tych vlakien je uz tolko, ze naozaj netusim co funguje. je tu velmi vela vlakien :( Diky za pomoc !

**Comment by TheGuyOnChair** [comment]
> Pekny den, prosim ktory fork momentalne funguje s rychlejsim stahovanim? Niekto v starych vlaknach doporucil pouzit nizsiu verziu, ale tych vlakien je uz tolko, ze naozaj netusim co funguje. je tu velmi vela vlakien :( Diky za pomoc !

Ahoj, tu verzi, kterou tam mám já, to je 3.1.0 s pythonem 3.9, 
postupoval jsem hlavně podle tohohle návodu, ten byl nejlepší. 
https://github.com/setnicka/ulozto-downloader/issues/101

Rychlost pravděpodobně prostě neovlivníš už jen kvůli Toru. 
Nic víc nejde dělat. Je mi to líto.

**Comment by TheGuyOnChair** [comment]
No, co se dá dělat. Já přinejmenším poděkuji panu @setnicka za tenhle program na kterém pracoval. I všem ostatním, kteří se na tom podíleli. Bylo mi ctí použít tento program :D
