### ISSUE TITLE
Rip uložto

### ISSUE THREAD

**Issue by Bob4716** [setnicka/ulozto-downloader#188]
,,1. 12. 2023 došlo k výrazným změnám ve fungování cloudového úložiště Ulož.to Disk a PINKfile.cz. Změny jsou vynucenou reakcí na přicházející evropskou legislativu označovanou jako DSA.
Služby cloudového úložiště jsou od pátku 1. 12. 2023 přístupné pouze registrovaným uživatelům. **Nově je obsah přístupný pouze těm uživatelům, kteří jej na úložiště sami nahráli.**
Pokud za nových podmínek nemají platící uživatelé zájem službu nadále využívat, mohou své účty ukončit, nebo převést na bezplatný plán FREE. V takovém případě jim mohou být navráceny i dříve zakoupené Datové balíčky nebo i předplatná, a to v poměrné výši podle jejich čerpání."

Snad tento code půjde do budoucna využit i na jiné stránky.

**Comment by pkejval** [comment]
FastShare.cloud

Někdo jim ukradl veškerý obsah na Seychely.

**Comment by pkejval** [comment]
Na netu tvrdí že je to mirror ulož.to

1. 12. 2023 15:31:13 Vojtak42 ***@***.***>:

**Comment by Vojtak42** [comment]
A nějaká bližší nápověda k tomu ulozisti by nebyla?😄

**Comment by origamirek** [comment]
> FastShare.cloud
> 
> Někdo jim ukradl veškerý obsah na Seychely.

Blbost, Fastshare je jen konkurenční služba. Schválně jsem si schoval několik odkazů na ulož.to a tyto soubory tam nejsou. Sám se divím, proč se ulož.to zkrátka nestane službou třeba z Konga, která bude nabízet náhodou i češtinu. Věřím, že by to šlo zařídit i bez fyzického stěhování serverů. Ale majitel si už asi nahrabal dost a za ten opruz mu to už nestojí. Prostě shořela další Alexandrijská knihovna, EU jásá.

**Comment by Vojtak42** [comment]
> > FastShare.cloud
> > Někdo jim ukradl veškerý obsah na Seychely.
> 
> Blbost, Fastshare je jen konkurenční služba. Schválně jsem si schoval několik odkazů na ulož.to a tyto soubory tam nejsou. Sám se divím, proč se ulož.to zkrátka nestane službou třeba z Konga, která bude nabízet náhodou i češtinu. Věřím, že by to šlo zařídit i bez fyzického stěhování serverů. Ale majitel si už asi nahrabal dost a za ten opruz mu to už nestojí. Prostě shořela další Alexandrijská knihovna, EU jásá.

Souhlas, ani zdaleka tam není to, co hledám.

**Comment by pkejval** [comment]
Omlouvám se za mystifikaci s tím fastshare.

2. 12. 2023 9:22:13 Vojtak42 ***@***.***>:

**Comment by Vojtak42** [comment]
A já iž doufal, že je tady nějaká kopie.
Btw Fastshare nesídlí na Seyshelách

**Comment by Fikus25** [comment]
Tady je videonávod pro ty, kteří ještě neví jak na to, návod je pro prohlížeč Opera, ale funguje to všude +- stejně.
[https://youtu.be/vDfD2Hk9WMg](url)

**Comment by origamirek** [comment]
Ano, hoďte to na yt, ať se k tomu co nejrychleji všichni dostanou, vůbec nehrozí další změny...

**Comment by Fikus25** [comment]
> Ano, hoďte to na yt, ať se k tomu co nejrychleji všichni dostanou, vůbec nehrozí další změny...

Je to neveřejně, jen přes odkaz

**Comment by Vojtak42** [comment]
Taky doufám, že to tu ulozto nemonitoruje.

**Comment by Fikus25** [comment]
> Tyhle věci se musí šířit interně, sem se dostane každý. Všechno co se takto zveřejní má jen krátkého trvání.

OK, deleted

**Comment by Vojtak42** [comment]
https://github.com/setnicka/ulozto-downloader/issues/185#issuecomment-1837088663

**Comment by Ghostman863** [comment]
a myslíte si že by šlo nástroj použít i na jinou stránku?? Fastshare, datoid....

**Comment by Bob4716** [comment]
> a myslíte si že by šlo nástroj použít i na jinou stránku?? Fastshare, datoid....

já si myslím že by to šlo ale muselo by se to překódovat na jiní web.. (Samozřejmě v tom nemam žádné zkušenosti jen si myslím že by to tak bylo :D)

**Comment by Vojtak42** [comment]
> > a myslíte si že by šlo nástroj použít i na jinou stránku?? Fastshare, datoid....
> 
> já si myslím že by to šlo ale muselo by se to překódovat na jiní web.. (Samozřejmě v tom nemam žádné zkušenosti jen si myslím že by to tak bylo :D)

https://github.com/setnicka/ulozto-downloader/issues/185#issuecomment-1836408677
