### ISSUE TITLE
Stahovanie z pornfile.cz nefunguje

### ISSUE THREAD

**Issue by sinepgnol** [setnicka/ulozto-downloader#27]
Zdravim,

nebolo by mozne pridat aj stahovanie zo serveru pornfile.cz, partnerskeho serveru uloz.zo? Momentalne mi to nefunguje, vyhadzuje nasledovnu chybu:
```
user@Mac-Pro Documents % python3.8 /Users/user/documents/ulozto_downloader-master/ulozto_downloader.py --parts 20 --output /Users/user/documents/ "https://pornfile.cz/file/F4FlzI3tldtS/rychly-prachy-cikanky-z-chanova-2-27-11-2019-mp4"
Starting downloading for url 'https://pornfile.cz/file/F4FlzI3tldtS/rychly-prachy-cikanky-z-chanova-2-27-11-2019-mp4'
Getting info (filename, filesize, ...)
Cannot download file: Cannot parse Uloz.to page to get download information, no slowDownload URL and no CAPTCHA challenge URL found
user@Mac-Pro Documents % 
```
Vopred diky.

**Comment by JanPokorny** [comment]
@setnicka Pornfile.cz ukládá informaci o odkliknutí 18+ dialogu do session. Je nutné tento dialog "odkliknout" ještě před requestem samotného souboru. (Samozřejmě se to vzhledem k tomu, že každé vlákno má vlastní session, musí udělat pro každé.) Nicméně to je poměrně easy fix, v tom kódu co Vžum co jsem ti naposledy posílal to najdeš.

**Comment by sinepgnol** [comment]
@JanPokorny Otazku som polozil ja, ale vy ste odpovedali uzivatelovi @setnicka. Mohli by ste mi prosim poslat tu opravu kodu aj mne? Dakujem. Rad by som si stiahol uvedene videjo.

**Comment by JanPokorny** [comment]
@sinepgnol Ano, dobrý postřeh, opravdu jsem to neříkal vám, ale autorovi tohoto repozitáře. Pokud chcete stahovat videjo, můžete použít http://vzum.8u.cz/

**Comment by sinepgnol** [comment]
@JanPokorny Vpohode, nic sa nestalo. Bohuzial ficim na macOS alebo Linuxe, do Windowsu uz dlhsiu dobu nefusujem. Z tohto dovodu uprednostnujem pouzitie tohto programu v prikazovom riadku.

**Comment by JanPokorny** [comment]
@sinepgnol Vžum funguje v Mono na Linuxu, vím že existují lidé kterým se to povedlo u sebe rozchodit. Pro macOS existuje Mono taky, ale nevím o nikom komu by se povedlo úspěšně Vžum spustit tam (teoreticky to možné je). Můžete zkusit.

**Comment by sinepgnol** [comment]
Rozumiem, ale ja by som aj tak preferoval Vzum spustal cez prikazovy riadok, preto by som rad nasiel riesenie ako stahovat aj z Pornfile.cz aby som si tie ciganky mohol kuknut v HD kvalite.

**Comment by muniv11111** [comment]
taky se připojím...mrkli byste na ten pornfile? aby to jelo i s nynější novou verzí.. ☺

**Comment by setnicka** [comment]
Tak jsem vám udělal radost ;)

**Comment by muniv11111** [comment]
> Tak jsem vám udělal radost ;)

super, tak jsem to nějak měl v tom mém kódu, ale nevěděl kam to nejlíp dát do tvého... :-)

**Comment by sinepgnol** [comment]
> Tak jsem vám udělal radost ;)

Dakujeme. Predsa len mam s jednym video z pornfile problem, konkretne s tymto, kde sa to zasekne na _"[CAPTCHA solve]	CAPTCHA image challenge..."_ 

`ulozto-downloader --output ~/Downloads --auto-captcha https://pornfile.cz/file/bdDluW2POaoo/manyvids-purple-bitch-maleficent-loves-to-fuck-2160p-60fps-mp4            `
ale napriklad toto video islo bez problemov:
` ulozto-downloader --output ~/Downloads --auto-captcha https://pornfile.cz/file/USX3Vd7hZCJk/kreme-farting-sluts-maria-devine-vanessa-vaughn-nina-heaven-interracial-anal-dp-dap-rs110-mp4`

Kde moze byt problem?

**Comment by muniv11111** [comment]
mohu potvrdit taky mi tohle nejde: https://pornfile.cz/file/bdDluW2POaoo/manyvids-purple-bitch-maleficent-loves-to-fuck-2160p-60fps-mp4  

Starting downloading for url 'https://pornfile.cz/file/bdDluW2POaoo/manyvids-purple-bitch-maleficent-loves-to-fuck-2160p-60fps-mp4'
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed

[34m[CAPTCHA solve]	[0mCAPTCHA image challenge...[K 

není toto ale náhodou příme stahování bez captchy a na to to visí.. nechybí nekde v kodu podmínka jen na tohle?

**Comment by muniv11111** [comment]
Na pornfile existuje verze stahování bez captchy kdy v těle stránky je text: "js-free-download-button-direct"

Týká se to toho odkazu co jsem dal nad tím třeba.. už jsem si to upravil a jede mi to..

**Comment by sinepgnol** [comment]
> Na pornfile existuje verze stahování bez captchy kdy v těle stránky je text: "js-free-download-button-direct"
> 
> Týká se to toho odkazu co jsem dal nad tím třeba.. už jsem si to upravil a jede mi to..

Ako si to upravil prosim ta?

**Comment by muniv11111** [comment]
> > Na pornfile existuje verze stahování bez captchy kdy v těle stránky je text: "js-free-download-button-direct"
> > Týká se to toho odkazu co jsem dal nad tím třeba.. už jsem si to upravil a jede mi to..
> 
> Ako si to upravil prosim ta?

https://master.tus.io/files/88420c33174127b602a797b94c6858ee+MVJxxoIsFFkwT.1WDYs7z9ZleIrI3O2IjATtUogY0iaXidLfKqAdw5hX6QkiLFr9U6wHz5nZC7uKs6UAow6FN7c0.xwFDT96ngi_K_0h8rhFbNkPADNdNWiqo_3gqcTQ

zkus tyhle 2 soubory v zipu.. ale ted mi to píše furt limit exceeded jak jsem to zkoušel víckrát na tom linku.. tak uvidíš.. je to narycho splácané.. raději at to @setnicka upraví profi pak.. :-)

**Comment by muniv11111** [comment]
zjistuju že je tam taky problém s omezením uloz.to.. takže bych to že mi to jede vzal zpět... stahuje to některé části, ale padá to často na free limit exceeded nebo to hází hlášku:  code 429, viz:

https://stackoverflow.com/questions/22786068/how-to-avoid-http-error-429-too-many-requests-python

**Comment by setnicka** [comment]
Bohužel se mi to nepovedlo vyřešit, jen jsem zlešil hlášky ulozto-downloaderu, aby bylo jasnější, co zkouší.

Takže dokud někdo nevymyslí, jak obcházet nové mechanismy zavedené Uloz.to (v odpovědi asi i na podobné automatické stahovače), tak s tím moc nehneme :(

**Comment by setnicka** [comment]
Tak jsem se na to podíval a rozlousknul to. Ono totiž u některých downloadů pro zmatení uživatele je link tvářící se stejně jako kdyby na jeho konci měla číhat CAPTCHA... ale namísto toho vrátí přímo 302 redirect a dá se rovnou stahovat. Teď už to kód detekuje, funguje ve verzi 1.7.1.

**Comment by muniv11111** [comment]
Super - zkouším to pořád na tom vzorovém linku tady: dám 10 parts - jedou dvě vlákna, za cca 40 sec se rozjela další dvě a pak za dalších cca 40 sec se rozjelo zbylych 6 vláken temer současně... funguje jenom u tohodle typu linku tak nebo jak bys to viděl tohle chování?
