### ISSUE TITLE
ulozto-downloader na Windows 10

### ISSUE THREAD

**Issue by sebastian7722** [setnicka/ulozto-downloader#38]
Povedlo se vám to někomu zprovoznit na Windows 10 ?
mě to píše chybu:

python downloader.py --parts 16 "https://uloz.to/file/8THNi4MCBpeQ/narwhals-mp3"

> Traceback (most recent call last):
  File "downloader.py", line 10, in <module>
    from .page import Page
ImportError: attempted relative import with no known parent package

verze pythonu 3.8

**Comment by Koticka** [comment]
Ahoj, pouštíš to špatně. Spouštět se má skript ulozto-downloader.

Viz příklad z README
```shell
ulozto-downloader --auto-captcha --parts 15 "https://ulozto.cz/file/TKvQVDFBEhtL/debian-9-6-0-amd64-netinst-iso"
```
Momentálně to teďka ale moc nefunguje, protože ulozto přidalo další ochranu. Bude ti to stahovat max 2x tak rychle (více než dvě vlákna se nevytvoří, ani když to nastavíš).

**Comment by Aryan6977** [comment]
![cmd](https://user-images.githubusercontent.com/74857247/99901503-5ca6ba80-2cb7-11eb-8703-3402aae82a50.PNG)
![package](https://user-images.githubusercontent.com/74857247/99901505-5d3f5100-2cb7-11eb-815e-6db59fe78fc4.PNG)

Omlouvám se ale nemám s pythonem žádné zkušenosti, příkaz mi nefunguje.

**Comment by Koticka** [comment]
Vždycky jsem to instaloval přes clone, s tímto nemám zkušenosti. @setnicka ?

**Comment by JanPokorny** [comment]
Well, tak jak to @setnicka přidal do pipu to bohužel nemá Windows podporu, `#!` není na Windows validní formát spustitelného souboru 😆 Ale přes clone to půjde.

@Aryan6977 Postup by měl být:
```bash
git clone https://github.com/setnicka/ulozto-downloader.git
cd ulozto-downloader
pip install -r requirements.txt
python ulozto-downloader --help
```

...a dále příkazy spouštět pomocí `python ulozto-downloader [argumenty...]`.

**Comment by JanPokorny** [comment]
...ale pro ušetření zklamání musím zdůraznit že to fakt momentálně umí max 2 vlákna. GUI http://vzum.8u.cz to už má vyřešené, ale tady je to ještě TODO (#37)

**Comment by Aryan6977** [comment]
Zprovoznit se mi to povedlo ale ukazuje to nějakou chybu :
![screenshot](https://user-images.githubusercontent.com/74857247/100470999-a1788a00-30d9-11eb-8a8b-da4103875b03.png)
V době když sem tu psal poprvé tak Vžum! nefungoval ale už funguje a běží stahování naplno. Díky za návod doufám že pomůže ostatním.

**Comment by sinepgnol** [comment]
Mne pise tuto istu chybu na Macu. Cudujem sa, pretoze pred poslednou aktualizaciou vsetko fungovalo bez problemov.

**Comment by muniv11111** [comment]
není to opět tohle https://github.com/setnicka/ulozto-downloader/issues/33 ? máte nejnovejsí verzi?

**Comment by sinepgnol** [comment]
Ano, je to ono, vlozil som tam aj svoju konkretnu chybu. Ak budete mat cas tak sa na to prosim pozrite.

**Comment by axel845845** [comment]
@sebastian7722 Funguje to stále ve Windows?

**Comment by sebastian7722** [comment]
@axel845845 Nejspíš ne.. Zkusil sem to s verzí pythonu 3.9, ostatní verze byly na tom stejně myslím.
![image](https://user-images.githubusercontent.com/74857247/144303715-8b690f47-188e-4628-ba42-2b9635c65406.png)

**Comment by setnicka** [comment]
Duplicated #70 

Mělo by být (konečně) vyřešeno #93 a novou verzí [3.0.0](https://pypi.org/project/ulozto-downloader/3.0.0/)
