### ISSUE TITLE
Stahování model.tflite je hrozně pomalé a selže před koncem

### ISSUE THREAD

**Issue by domestomas** [setnicka/ulozto-downloader#39]
Mám problém se stažením model.tflite, nejde stáhnout ani pomocí tvého kódu, ani normálně z prohlížeče (download se pořád zpomaluje a časem selže, přestože máme na kolejích rychlost ~100Mbit/s), nakonec se mi to povedlo wgetem. Pokud je to u ostatních podobné, bylo by asi fajn si ho někam nahrát a stahovat odjinud.
Díky

Tom

**Comment by Koticka** [comment]
Nemám ten problém. Pokud přetrvává, zkus do root adresáře projektu stáhnout model manuálně, url https://github.com/JanPalasek/ulozto-captcha-breaker/releases/download/v2.2/model.tflite

**Comment by JanPokorny** [comment]
Tohle je notorický problém GitHub releases, který se vyskytuje u některých českých ISP. Netuším co to způsobuje. Týká se to jen a pouze GitHub releases, ani ne celého GitHubu, a děje se to jen občas.

**Comment by domestomas** [comment]
Máš pravdu, dneska už to funguje :D Uzavírám.
