### ISSUE TITLE
Chyba při stahování

### ISSUE THREAD

**Issue by VixikHD** [setnicka/ulozto-downloader#46]
```
root@server:~/dwl# ulozto-downloader "https://uloz.to/file/3Qxb0y5ZAJuL/"
Starting downloading for url 'https://uloz.to/file/3Qxb0y5ZAJuL/'
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed

Traceback (most recent call last):, trying to solve
  File "/usr/local/bin/ulozto-downloader", line 48, in <module>
    main()
  File "/usr/local/bin/ulozto-downloader", line 44, in main
    d.download(args.url, args.parts, args.output)
  File "/usr/local/lib/python3.8/dist-packages/ulozto_downloader/downloader.py", line 168, in download
    download_url = next(self.captcha_download_links_generator)
  File "/usr/local/lib/python3.8/dist-packages/ulozto_downloader/page.py", line 169, in captcha_download_links_generator
    captcha_answer = captcha_solve_func("https:" + captcha_image_url, print_func=print_func)
  File "/usr/local/lib/python3.8/dist-packages/ulozto_downloader/captcha.py", line 18, in tkinter_user_prompt
    root = tk.Tk()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
root@server:~/dwl#
```

**Comment by kkoouu** [comment]
snazi se ti zobrazit dialog s captchou a nevi jak ... zkus treba z cmd pustit xclock a predpokladam, ze se objevi stejna chyba, poustit to zrejme z textoveho terminalu a ne z grafickeho prostredi ... a ten root no :)

**Comment by VixikHD** [comment]
U nějakých linků ten downloader fungoval perfektně (i z terminálu a s rootem :) ), ale s tímto (https://uloz.to/file/3Qxb0y5ZAJuL/) má problém. Asi jsem to měl uvést už v té první zprávě..

**Comment by kkoouu** [comment]
já to zkusil a jede mi to ... ale používám --auto-captcha

**Comment by AbitTheGray** [comment]
Děje semi to samé z `Konsole`. Bash v `Dolphin` funguje OK.
Oboje s `--auto-captcha`

**Comment by kkoouu** [comment]
tak zkuste porovnat hodnotu promenne DISPLAY v obou prostredich ... ( echo $DISPLAY )

**Comment by AbitTheGray** [comment]
> tak zkuste porovnat hodnotu promenne DISPLAY v obou prostredich ... ( echo $DISPLAY )

`echo $DISPLAY` je v obou případech `:0`
V `Konsole` jsem zkoušel `xclock` a fungoval.

**Comment by kkoouu** [comment]
zajimavy .... tak mozna jeste nejaky rozdil pri vypisu vsech promennych ( set ) ?

**Comment by setnicka** [comment]
Zavírám jako pravděpodobně vyřešené. Pokud problém přetrvává, tak reopen.
