### ISSUE TITLE
zlepseni ui

### ISSUE THREAD

**Issue by mazmar** [setnicka/ulozto-downloader#47]
kdyz dam hodne moc casti (500 pro 10GB, 1000 pro 20gb) tak ui prestane po +-50 davat smysl a musim mit consoli otevrenou naplno.

mozna misto progresu pro kazdou cast by to slo nejak optimalizovat na ui o +- 4 radcich
se statusem jak je ted uplne dolu
1 radek celkovy progres, + celkova rychlost (tohle je vice mene nejdulezitejsi udaj)
1 radek pocet aktivnich casti, pocet skoncenych casti, pocet cekajicich, pocet startujicich

**Comment by pkejval** [comment]
Jelikož to používám ve skriptu, tak by se mi líbilo úplně vypnout celé TUI. Jestli někdy najdu čas, tak zkusím udělat kdyžtak poslat PR.

**Comment by setnicka** [comment]
Základ pro změny/vypínání frontendu jsou v PR #94, za pár dní (až se to uleží a až mě napadne, jestli jsem tam něco neudělal špatně) to mergnu do masteru a vydám další verzi. S pomocí tohohle by mělo jít postavit nějaké "short" konzolové rozhraní jen se statusem i udělat tomu nějaký výstup pro lepší použití ve skriptech.

Budu rád za názory k PR :)

**Comment by setnicka** [comment]
A sorrry, že změny trvají tak dlouho, tohle je pro mě low-maintenance hobby projekt, ke kterému se dostanu jednou za dlouhý čas.

**Comment by setnicka** [comment]
#94 mergnuto, pull request na nějaké "short" konzolové rozhraní vítaný :)

**Comment by setnicka** [comment]
Díky mergnutému pull requestu je ve verzi 3.2.0 už v defaultu vypnuté vypisování částí (dá se zapnout pomocí `--parts-progress`). Takže by z hlediska konzolového rozhraní nemělo nic bránit používat dělení na stovky částí.

Budu rád ze feedback na další vylepšení.
