### ISSUE TITLE
[REQ] Uloz.to -> Gdrive in colab

### ISSUE THREAD

**Issue by forart** [setnicka/ulozto-downloader#54]
Hi there, 
do you think is possible to add your script to [MixLab](https://github.com/shirooo39/MiXLab) project ?

Note I've already requested to the author (@shirooo39) here:
https://github.com/shirooo39/MiXLab/issues/7

Thanks

**Comment by setnicka** [comment]
Hi, I looked at MixLab project and I am a little bit confused. I don't know how to add something like ulozto-downloader into IPython notebook, never done it before.

Is work on this side or on the side of MixLab needed?

**Comment by forart** [comment]
> I don't know how to add something like ulozto-downloader into IPython notebook, never done it before.
>
Nor I. 

Please ask @shirooo39 on MixLab's github: https://github.com/shirooo39/MiXLab/issues/7

**Comment by setnicka** [comment]
Closing as won't do.
