### ISSUE TITLE
problém s --auto-captcha

### ISSUE THREAD

**Issue by jignac05** [setnicka/ulozto-downloader#55]
Getting info (filename, filesize, ...)
CAPTCHA protected download - CAPTCHA challenges will be displayed

Starting TOR...
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/-/.local/bin/ulozto-downloader", line 8, in <module>
    sys.exit(run())
  File "/home/-/.local/lib/python3.9/site-packages/uldlib/cmd.py", line 44, in run
    d.download(args.url, args.parts, args.output)
  File "/home/-/.local/lib/python3.9/site-packages/uldlib/downloader.py", line 237, in download
    download_url = next(self.captcha_download_links_generator)
  File "/home/-/.local/lib/python3.9/site-packages/uldlib/page.py", line 278, in captcha_download_links_generator
    captcha_answer = captcha_solve_func(
  File "/home/-/.local/lib/python3.9/site-packages/uldlib/captcha.py", line 92, in __call__
    interpreter = tflite.Interpreter(model_content=self.model_content)
  File "/home/-/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 382, in __init__
    _interpreter_wrapper.CreateWrapperFromBuffer(
SystemError: <built-in method CreateWrapperFromBuffer of PyCapsule object at 0x7f6a22d55150> returned a result with an error set
Terminating tor..
Removed tor data dir: tor_data_dir_2e92ae68-d4cd-45bc-9c29-59119c500b1f

Jméno home adresáře jsem zaměnil za "-"

**Comment by jignac05** [comment]
Když jsem zrušil --auto-captcha tak už mi to jede bez problémů

**Comment by AtamiiX** [comment]
Pokud jsi na Linuxové distribuci vycházející z debianu nainstaluj tflite_runtime přes tohle "pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime"
Mě to pomohlo

**Comment by jignac05** [comment]
Používám Ubuntu 21.04. Tfline jsem už několikrát reinstalloval z různých balíčků. Žádný nepomohl, stále stejný error.

**Comment by AtamiiX** [comment]
Chybí ti numpy. Nainstaluj takhle:
Git clone https://github.com/setnicka/ulozto-downloader.git nebo stáhni a extrahuj.
cd ulozto-downloader
pip install -r requirements.txt
pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime

a zkus
python ulozto-downloader.py --auto-captcha ---parts 15 https://ulozto.cz/file/3JUvRLpILIut/debian-10-9-0-amd64-netinst-iso

**Comment by jignac05** [comment]
pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime
Looking in indexes: https://pypi.org/simple, https://google-coral.github.io/py-repo/
ERROR: Could not find a version that satisfies the requirement tflite_runtime
ERROR: No matching distribution found for tflite_runtime

**Comment by jignac05** [comment]
auto chaptcha mi stále nefunguje

**Comment by AtamiiX** [comment]
Pokud stále nefunguje, otevři složku ulozto-downloader z terminálu, a vlož "sudo python3 setup.py install"

**Comment by AtamiiX** [comment]
Nedávno jsem zkoušel Arch Linux a narazil na stejný problém. Prý je to pythonem...
Nejdřív nainstaluj brew (homebrew) přes /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
pak si ho přidej do path přes eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
zkontroluj jestli brew jede přes brew doctor
pak nainstaluj gcc brew install gcc
downgradni python na 3.6 přes 
 brew unlink python
 brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/e128fa1bce3377de32cbf11bd8e46f7334dfd7a6/Formula/python.rb
 brew switch python 3.6.5

pak nainstaluj tflite "pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime"
