### ISSUE TITLE
WARNING: File '{filename}' already exists, overwrite it? [y/n]

### ISSUE THREAD

**Issue by owinter92** [setnicka/ulozto-downloader#59]
Hi, great piece of software however suppose you want to do something like this:
```
while IFS= read -r line; do
    ulozto-downloader --auto-captcha --parts 50 $line
done < to_download.txt
```
It would be really convient if you cound add another parameter, say --Y or --N, that would do the obvious thing here.

**Comment by stinovlas** [comment]
Can't you achieve the same result by using `yes` or `yes n` respectively?
```bash
while IFS= read -r line; do
    yes | ulozto-downloader --auto-captcha --parts 50 $line
done < to_download.txt
```

**Comment by owinter92** [comment]
Possibly (I need to test it) but not in the case of No because after No the script returns exit(1) and it kill the whole loop.

**Comment by stinovlas** [comment]
> Possibly (I need to test it) but not in the case of No because after No the script returns exit(1) and it kill the whole loop.

`sys.exit(1)` only means that the script terminates with exit status 1. Why wouldn't it continue with the next loop iteration? That's not how the POSIX shell while loop behaves. `yes n | ulozto-downloader ...` should work like a charm.

**Comment by owinter92** [comment]
Indeed you are right. I was a little bit confused because if I tried to do it by hand the loops stopped. Thanks.
