### ISSUE TITLE
[Bug?] Errno 24: Too many open files

### ISSUE THREAD

**Issue by Pheggas** [setnicka/ulozto-downloader#64]
Ahoj, momentálne som dal sťahovať 10gb video z uložto pri 750 partoch. To mi hneď napísalo error `Errno 24: Too many open files`. Postupne som znižoval až na 499 kde to vyzeralo byť ako tak v pohode. Ale po nejakých 40 partoch to začalo hádzať errory pomedzi riadky sťahovania. Pripojenia ktoré už boli nadviazané sa dosťahovali a odvtedy to stálo a žiadne nové pripojenia sa nevytvárali. Momentálne to skúšam len so 100 partami tak hádam to bude lepšie.

Máte niekto nejaký fix? 

PS: Našiel som niečo [takéto](https://stackoverflow.com/questions/18280612/ioerror-errno-24-too-many-open-files)

**Comment by setnicka** [comment]
Staré issue. Zavírám s "wontfix", protože tohle je spíše na nastavení ulimitu v systému.

Zatím nejsem přesvědčený, že by to měl nějak řešit ulozto-downloader.
