### ISSUE TITLE
Log do souboru

### ISSUE THREAD

**Issue by hundera** [setnicka/ulozto-downloader#65]
Ahoj, díky za super program.
Je možné upravit výstup tak aby to šlo pustit na pozadí a logovat do souboru? 
Aktuálně tím vznikne naprosto nečitelný log soubor, ze kterého není poznat co už stáhnul.
díky

**Comment by Dacesilian** [comment]
Přidávám hlas k tomuto požadavku. Bylo by super mít možnost spustit downloader programově na pozadí a číst stav stahování.

**Comment by setnicka** [comment]
Díky mergnutí #94 by k tomuhle teď měla být snadnější cesta.

**Comment by setnicka** [comment]
Základní log do souboru implementován ve verzi 3.2.0. Upgrade pomocí:
```shell
pip3 install --upgrade ulozto-downloader
```

Log se dá zapnout přepínačem `--log <LOGFILE>` a loguje základní set událostí (vyjma progress věcí, tedy neloguje za každou část dvakrát za sekundu stažené bajty). Asi ej to ještě k vylepšování, ale už aspoň funguje :)
