### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by axel845845** [setnicka/ulozto-downloader#66]
I have this error, I really don't know if I'm doing it right, can anyone help me? I would be very grateful and I am on Windows 10, Thank you
![1](https://user-images.githubusercontent.com/84351668/141181801-cf6d1d4a-ba72-492d-85ec-f188886febc0.png)
.

**Comment by setnicka** [comment]
Old issue, but fixed now. Probably entered URL without `https://` and this was an unhandled error. It is now handled correctly plus autofixing of URLs without `https://` is also added.
