### ISSUE TITLE
ulozto-downloader nefunguje na windows 10 

### ISSUE THREAD

**Issue by misalibaytb** [setnicka/ulozto-downloader#70]
chtěl bych se zeptat proč mi nejde ulozto-downloader na windows 10 když jsem to poprvé skusil šlo to ale pak už ne pak už to začalo dávat tuto chybu
![image](https://user-images.githubusercontent.com/66683443/149590265-39edabea-d7be-46d8-b7b2-16aa124a4f82.png)
nevíte někdo co stím zkoušel jsem přeinstalovat python znovu zkopírovat ty soubory aby byly originální ale stále nic

**Comment by Mineplayerminer** [comment]
rovnaký problém, spúšťaj to z Linuxu (VMWare napríklad)

**Comment by zbyna** [comment]
Nebo alternativa pouze pro windows tady:
``
http://vzum.hys.cz/
``

**Comment by Mineplayerminer** [comment]
> Nebo alternativa pouze pro windows tady: `http://vzum.hys.cz/`

Ďakujeeem! Funguje to perfektne.

**Comment by frixten** [comment]
jenom já to chci v pythonu

**Comment by frixten** [comment]
> Nebo alternativa pouze pro windows tady: `http://vzum.hys.cz/`

a paktéž to nejde ani na linuxu (ubuntu desktop, ubuntu server, debian desktop, debian server)

**Comment by Vojtak42** [comment]
@misalibaytb pip install git+https://github.com/Vojtak42/ulozto-downloader.git
Tady mám přidané potřebné pull requesty od @zbyna a @hroncok.

**Comment by setnicka** [comment]
Mělo by být vyřešeno #93 a novou verzí [3.0.0](https://pypi.org/project/ulozto-downloader/3.0.0/)
