### ISSUE TITLE
TOR access denied 

### ISSUE THREAD

**Issue by clovdystackflow** [setnicka/ulozto-downloader#75]
when trying to install a file, everything goes fine until it has to use tor, says it's not in my PATH but it's installed

**Comment by vladodriver** [comment]
which tor
/usr/bin/tor

**Comment by setnicka** [comment]
Does this problem still persist? I added some hints how to install Tor into README:
*Linux: `apt get install tor`
* Windows: install TorBrowser and add directory with `tor.exe` to system `%PATH%`

**Comment by setnicka** [comment]
Old issue, but info for others: See updated README, the part about setting Windows `%PATH%` was updated.
