### ISSUE TITLE
Problém pri sťahovananí toho istého súboru

### ISSUE THREAD

**Issue by marioqqq** [setnicka/ulozto-downloader#98]
Skúšam release 3.0.0 a ak dám sťahovať už stiahnutý súbor, tak mi vyhodí nasledujúci error.
![image](https://user-images.githubusercontent.com/93001533/183931673-d1ac0069-f1be-4fb6-8106-e124cb178941.png)
Program mi beží na Raspberry s Raspbianom.

**Comment by setnicka** [comment]
Řádek 208 je divný, to je o pár řádků offsetnuté jinak. Navíc přímo tam to skočí jen, když už hlavní smyčka frontendu nastartuje s tím, že chce rovnou skončit. Ale přidal jsem tam opravu, které řeší i tuhle situaci. Verze 3.0.1.

**Comment by marioqqq** [comment]
![image](https://user-images.githubusercontent.com/93001533/184094085-b95bddcb-d313-4e6e-8f42-6e51c586735c.png)
Forkol som si opravenú verziu a teraz vypíše takúto chybu.
Áno riadkovanie nesedelo, lebo som si tam pre WEB-ui dopisoval niečo, teraz som to ale skúšal hneď po git clone.

**Comment by setnicka** [comment]
Jo to bude souviset s tím, že se to z nějakého důvodu rozhodne všechny spuštěné thready skončit ještě předtím, než vlastně nastartují. Vypadá to, že se na to budu muset podívat víc. Díky za report.
