### ISSUE TITLE
Not working downloading due to AttributeError

### ISSUE THREAD

**Issue by lukynmatuska** [setnicka/ulozto-downloader#99]
For more info see attached screenshot. I tried uninstall and install again package, but It didn't help.
![Screenshot_20220811_150714](https://user-images.githubusercontent.com/19732513/184140327-63d579f5-9f37-413c-a9b1-81ada8506cbd.png)

**Comment by setnicka** [comment]
Fixed in version 3.2.0. Upgrade using:
```shell
pip3 install --upgrade ulozto-downloader
```

You entered URL without `https://` and this was an unhandled error. It is now handled correctly plus autofixing of URLs without `https://` is also added.

**Comment by lukynmatuska** [comment]
Now it works. Thank you very much!
